### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by Dqrshan** [Dqrshan/discord-debug#2]
- [x] `sql` command (support for MySQL).
- [ ] ~~`git` command (advanced).~~
- [x] `docs` command (discord.js:main)
- [x] "**loadDefaultListeners**" option for `messages` & `interactions` for users to handle the commands by themselves, if they wish to do so.
Example:
```ts
import { Debugger, commands } from 'discord-debug';

// @example (soon)
const debug = new Debugger(client, {
    loadDefaultListeners: {
        message: false,
        interaction: false
    }
});

client.on('messageCreate', async (message) => {
    // handle commands by yourself using "commands" imported collection
    // > "messageRun()" for messages.
})

client.on('interactionCreate', async (interaction) => {
    // > "interactionRun()" for interactions.
});
```

### Join our [discord](https://dsc.gg/lorenz) for latest updates, suggestions and feature requests!

**Comment by AlmightyNan** [comment]
ok

**Comment by almightynan** [comment]
- [x] `stats` command (view machine's stats/info)

### This will include:
- disk usage
- network usage
- uptime
- gpu usage
- system temperature
- process count
- file system info
- system load
- os info
- disk i/o
- memory usage

**Comment by Dqrshan** [comment]
### Added `sql` command!

![sql](https://github.com/Dqrshan/discord-debug/assets/77528189/3c25bd45-227d-4fda-98d1-eb3f664cf495)

**Comment by Dqrshan** [comment]
completed [v2.1.0](https://github.com/Dqrshan/discord-debug/releases/tag/2.1.0)
